### ISSUE TITLE
Vis kun neste dato

### ISSUE THREAD

**Issue by kennethnilssen** [BobTheShoplifter/HomeAssistant-Posten#1]
Hei, 

Veldig bra integrasjon, men ønsker at i Lovelace vises kun den kommende dato, og ikke alle fremtidige datoer. 
Mulig å legge til en sånn funksjon/ sensor?

**Comment by jenscski** [comment]
Du kan benytte en template for å få ut verdien, frem til det kanskje kommer en mulighet rett i integrasjonen

Jeg sitter med en følelse av at jeg enten har missforstått noe, eller så er data i sensoren av en type jeg ikke skjønner så mye av, men følgende template fungerer hos meg.

`{{ states('sensor.posten_sensor') | replace('\'', '"') | from_json | first() }}`

**Comment by kennethnilssen** [comment]
Kom over en annen sensor som gjør dette, så kanskje @BobTheShoplifter kan legge til noe slikt?

```
#Posten
-   platform: rest
    name: postlevering
    resource: https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/1?postCode=0000 #ditt postnummer
    headers:
        x-requested-with: XMLHttpRequest
    scan_interval: 57600
    value_template: "{{ value_json.nextDeliveryDays[0] }}"
```
